fact_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views 

urlpatterns = [
    path('', views.access, name='access'),  # Set access as the first page to show up
    path('index/', login_required(views.HomeView.as_view()), name='index'),  # Apply login_required to the index page
    path('add_customer/', views.AddCustomerView.as_view(), name='add_customer'),
    path('add-invoice/', views.AddInvoiceView.as_view(), name='add-invoice'),
    path('view-invoice/<int:pk>/', views.InvoiceVisualizationView.as_view(), name='view-invoice' ),
    path('invoice-pdf/<int:pk>/', views.get_invoice_pdf, name="invoice-pdf"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('change_password/', views.change_password, name='change_password'),
    path('generate-pdf/<int:invoice_id>/', views.generate_pdf, name='generate_pdf'),
    
    path('commande/', views.AddCommandeView.as_view(), name='commande'),
    path('commande_list/', views.CommandeListView.as_view(), name='commande_list'),
    path('view-commande/<int:pk>', views.CommandeVisualizationView.as_view(), name='view-commande'),
    path('facture_avoir/<int:pk>/', views.InvoiceAvoir.as_view(), name='facture_avoir' ),
   
    path('delete_commande/<int:id>/', views.delete_commande, name='delete_commande'),



   
      



  
    

]

gestion_facture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls, name='admin2'),
    path('',include('fact_app.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('fact_app.urls')),
)

if settings.DEBUG : 
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fact_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator
from django.db import models




class Customer(models.Model):
    """
    Name: Customer model definition
    """
    
    name = models.CharField(max_length=132)

    #email = models.EmailField()

    #phone = models.CharField(max_length=132)
    address = models.CharField(max_length=300, default='Unknown Address')



    city = models.CharField(max_length=32)

    zip_code = models.CharField(max_length=16)
    ICE = models.IntegerField(default=0)
    CP = models.IntegerField(default=0)
    CIF= models.IntegerField(default=0)

    created_date = models.DateTimeField(auto_now_add=True)

    save_by = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta: 
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return self.name     



class Invoice(models.Model):
    """
    Name: Invoice model definition
    Description: 
    Author: elidrissisiham2@gmail.com
    """

    INVOICE_TYPE = (
        ('I', _('Import')),
        ('V', _('Vente TFZ'))
    )

    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)

    save_by = models.ForeignKey(User, on_delete=models.PROTECT)

    invoice_date_time = models.DateTimeField(auto_now_add=True)

    total = models.DecimalField(max_digits=10000, decimal_places=2)

    last_updated_date = models.DateTimeField(null=True, blank=True)

    paid  = models.BooleanField(default=False)

    invoice_type = models.CharField(max_length=1, choices=INVOICE_TYPE)

    comments = models.TextField(null=True, max_length=1000, blank=True)

    invoice_number = models.PositiveIntegerField(
        unique=True,
        null=True,
        blank=True,
        validators=[MaxValueValidator(999999)] )
    
    order_number= models.CharField(default='',max_length=200000000)

    remorque_number=models.CharField(default='',max_length=1000)

    total_nbre_gb = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_poid_kg = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    class Meta:
        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"

    def __str__(self):
           return f"{self.customer.name}_{self.invoice_date_time}"

    @property
    def get_total(self):
        articles = self.article_set.all()   
        total = sum(article.total for article in self.article_set.all())
        return total 
    
   
    
    def get_total_nbre_gb(self):
        total_nbre_gb = self.total_nbre_gb
        return total_nbre_gb

    def get_total_weight(self):
        total_weight = self.total_poid_kg
        return total_weight
    

class Commande(models.Model):
     """
    Name: Commande model definiton
    Descripiton: 
    Author: elidrissisiham2@gmail.com
    """
     customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
     save_by = models.ForeignKey(User, on_delete=models.PROTECT)
     commande_date_time = models.DateTimeField(auto_now_add=True)

     

     last_updated_date = models.DateTimeField(null=True, blank=True)
     commande_number = models.PositiveIntegerField(
        unique=True,
        null=True,
        blank=True,
        validators=[MaxValueValidator(999999)] )
     
     ref = models.CharField(default='',max_length=200000000)
     designation = models.CharField(default='',max_length=200000000)
     Qt = models.IntegerField(default=0)
     Prix = models.DecimalField(max_digits=100, decimal_places=2, default=0)
     Montant_HT= models.DecimalField(max_digits=100, decimal_places=2, default=0)
     Total_HT = models.DecimalField(max_digits=100, decimal_places=2, default=0)
     Total_TTC= models.DecimalField(max_digits=100, decimal_places=2, default=0)
     Poids= models.DecimalField(max_digits=100, decimal_places=2, default=0)

     class Meta: 
        verbose_name = "Commande"
        verbose_name_plural = "Commandes"

     def __str__(self):
           return f"{self.customer.name}_{self.commande_date_time}"
     
     @property
     def get_Montant(self):
        Montant_HT = self.Poids* self.Qt * self.Prix  
        return Montant_HT
     
     @classmethod
     def get_totalHT(cls):
        Total_HT = cls.objects.aggregate(total=models.Sum('Montant_HT'))['total'] or 0
        return Total_HT
     
     @classmethod
     def get_totalTTC(cls):
        Total_TTC = cls.objects.aggregate(total=models.Sum('Montant_HT'))['total'] or 0
        return Total_TTC
     
     def delete(self, *args, **kwargs):
        # Delete related CommandeItem objects
        self.commandeitem_set.all().delete()
        # Call the delete method of the superclass to delete the Commande instance
        super().delete(*args, **kwargs)
     

class CommandeItem(models.Model):

    customer = models.ForeignKey(Customer, on_delete=models.PROTECT,null=True, blank=True)
    commande = models.ForeignKey(Commande, on_delete=models.PROTECT, null=True, blank=True)

    ref = models.CharField(default='',max_length=200000000)
    designation = models.CharField(default='',max_length=200000000)
    Qt = models.IntegerField(default=0)
    Prix = models.DecimalField(max_digits=100, decimal_places=2, default=0)
    Poids= models.DecimalField(max_digits=100, decimal_places=2, default=0)
    Montant_HT= models.DecimalField(max_digits=100, decimal_places=2, default=0)

    def get_Montant(self):
        Montant_HT = self.Poids* self.Qt * self.Prix  
        return Montant_HT


    class Meta:
        verbose_name = 'CommandeItem'
        verbose_name_plural = 'CommandeItems'
   









     



class Article(models.Model):
    """
    Name: Article model definiton
    Descripiton: 
    Author: elidrissisiham2@gmail.com
    """

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)

    name = models.CharField(max_length=32)
    nbre_GB= models.IntegerField(default=0)


    quantity = models.IntegerField()

    unit_price = models.DecimalField(max_digits=1000000000, decimal_places=2)

    total = models.DecimalField(max_digits=1000000000, decimal_places=2)

    order_number = models.CharField(default='', max_length=20000000) #colis
    remorque_number = models.CharField(default='', max_length=10000000)


   

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    @property
    def get_total(self):
        total = self.quantity * self.unit_price   
        return total 
    
        

templates/add_customer.html
{% extends "base.html" %}

{% block content %}
<div class="container py-5">
    <div class="card">
        <div class="card-header bg-dark text-white">
            <h1 class="text-capitalize text-center m-0">Création d'un nouveau client/Fournisseur</h1>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}

                <div class="mb-3">
                    <label for="name" class="form-label">Nom</label>
                    <input name="name" required type="text" class="form-control" id="name" placeholder="">
                </div>

                

                <div class="row mb-3">
                    <div class="col-md-4">
                        <label for="ICE" class="form-label">ICE</label>
                        <input name="ICE" required type="number" class="form-control" id="ICE" placeholder="">
                    </div>

                    <div class="col-md-4">
                        <label for="CP" class="form-label">CP</label>
                        <input name="CP" required type="number" class="form-control" id="CP" placeholder="">
                    </div>

                    <div class="col-md-4">
                        <label for="CIF" class="form-label">CIF</label>
                        <input name="CIF" required type="number" class="form-control" id="CIF" placeholder="">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="address" class="form-label">Adresse</label>
                    <input name="address" required type="text" class="form-control" id="address" placeholder="">
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="city" class="form-label">Ville</label>
                        <input name="city" type="text" class="form-control" id="city" placeholder="">
                    </div>

                    <div class="col-md-6">
                        <label for="zip" class="form-label">Code postale</label>
                        <input name="zip" required type="text" class="form-control" id="zip" placeholder="">
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/avoir.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- CSS styles -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.4.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
<style>
    /* Typography */
    body {
        font-family: 'Arial', sans-serif;
        color: #333; /* Darker text color */
        background-color: #f9f9f9; /* Light background */
    }
    h4 {
        font-family: 'Arial', sans-serif;
        color: #0b519c; /* Blue header */
    }

    /* Invoice Container */
    .invoice-container {
        border: 1px solid #ddd;
        border-radius: 10px;
        background-color: #fff; /* White background */
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 30px;
        margin-top: 20px;
    }

    /* Header */
    .invoice-header {
        background-color: #fff; /* White background */
        color: #0b519c; /* Blue header */
        padding: 15px;
        border-radius: 10px 10px 0 0;
    }

    /* Logo */
    .invoice-logo {
        width: 100px;
        height: auto;
        margin-right: 10px;
    }

    /* Company Info */
    .company-info {
        margin-bottom: 20px;
    }

    /* Invoice Details */
    .invoice-details {
        margin-bottom: 30px;
        background-color: #fff; /* White background */
        color: #fdfafa; /* Darker text color */
        padding: 15px;
        border-radius: 10px;
    }

    /* Table */
    .table-bordered {
        border: 1px solid #ddd; /* Lighter border */
        background-color: #fff; /* White background */
        color : #333;
    }

    .table-bordered thead th {
        border: 1px solid #ddd; /* Lighter border */
        background-color: #f2f2f2;
        color : #333;
    }

    .table-bordered tbody td {
        border: 1px solid #ddd; /* Lighter border */
        color : #333;
    }

    /* Footer */
    .invoice-footer {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 0 0 10px 10px;
        border-top: 1px solid #ddd; /* Lighter border */
    }

    /* Print Button */
    .print-btn {
        margin-top: 20px;
    }

    .print-btn button {
        background-color: #0b519c; /* Blue button */
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .print-btn button:hover {
        background-color: #0a427a; /* Darker blue on hover */
    }

    /* Responsive Table */
    .table th,
    .table td {
        vertical-align: middle;
    }

    .table th {
        font-weight: bold;
    }

    .table th.bg-light,
    .table td.bg-light {
        background-color: #f2f2f2;
        color: #333;
    }

    .table th,
    .table td {
        border: 1px solid #ddd;
        padding: 8px;
    }

    .small-table {
        width: 50%;
        font-size: 0.8rem;
        background-color: #fff;
    }

    .small-table th,
    .small-table td {
        padding: 0.5rem;
    }

    /* Responsive Layout */
    @media print {
        .print-btn,
        .copyright {
            display: none;
        }
        .small-table {
    width: 100%; /* Ensure table fills the container */
    font-size: 18px; /* Adjust font size as needed */
    background-color: #fff; /* White background */
    border: 2px solid #1b1b1b; /* Lighter border */
    color: #333; /* Darker text color */
}

.small-table th,
.small-table td {
    padding: 8px; /* Adjust padding as needed */
    border: 1px solid #ddd; /* Lighter border */
    font-size: 16px; /* Adjust font size as needed */
}
        .invoice-footer {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            transform: none;
            width: auto;
        }
    /* Set page size to A4 */
    @page {
        size: A4;
        margin: 0; /* Reset default margins */
    }

    /* Adjust body and heading font sizes */
    body {
        font-size: 20px; /* Adjust to desired font size */
        color: #131313 !important; /* Change to desired color */
        margin: 0; /* Reset default margin */
    }

    h4 {
        font-size: 30px; /* Adjust to desired font size */
        color: #0b519c !important; /* Change to desired color */
        

    }
    .invoice-details p {
        color: #333 !important; /* Change to desired color */
    }
       /* Adjust layout for address and recipient information */
       .invoice-details .row {
        display: flex; /* Use flexbox layout */
        flex-wrap: wrap; /* Allow wrapping of flex items */
    }

    .invoice-details .col-md-6 {
        width: 50%; /* Each column takes up 50% of the row width */
    }

    /* Adjust padding and margin for elements as needed */
       /* Ensure the HTML and body elements fill the entire viewport */
       html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    .invoice-container {
        border: 1px solid #ffffff;
        border-radius: 10px;
        background-color: #fff; /* White background */
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 30px;
        width: 25cm; /* Width of A4 page */
        height: 35cm; /* Height of A4 page */
        margin: 0; /* Remove all margins */

    }

    
    /* Increase table font size and adjust column width */
    .table {
        font-size: 18px; /* Adjust to desired font size */
        width: 100%; /* Ensure the table fills the container */
    }
    .table td {
    font-weight: normal;
     }

    /* Black border for table */
    .table-bordered,
    .table-bordered thead th,
    .table-bordered tbody td {
        border: 2px solid #3b3b3b !important; /* Change to black color */
        color : #000 !important; /* Black text color */
         
    }
    .invoice-footer{
        font-size: 100px;
        width: 100%;
        font-size: 18px !important;
    }
    .montant-ht-cell {
    width: 150px;
                  }
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            
            <div class="invoice-container">
                <div class="invoice-header">
                   <h4 style="color: #0b519c;">Facture d'avoir N° {{ obj.invoice_number }}</h4>

                </div>
                <br>
                <div class="company-info text-center mb-4">
                    <img src="{% static 'images/logo2.jpg' %}" alt="BRUMARTEX" class="invoice-logo">
                    <h2>BRUMARTEX SARL AU</h2>
                    <p>IMPORT-EXPORT | SECOND HAND CLOTHES | FRIPERIE</p>
                </div>
                <br>
                <div class="invoice-details mb-4">
                    <div class="row">
                        <div class="col-md-6">
                            <p>Zone franche ilot N116 module N10, Tanger 90090, Maroc</p>
                            <p>Email: brumartex.logistique@gmail.com</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Destinataire : {{ obj.customer.name }}</strong></p>
                            <p><strong></strong> {{ obj.customer.address }}, {{ obj.customer.city }}</p>
                        </div>
                    </div>
                </div>

                
<div class="invoice-details mb-4">
    <div class="table-responsive">
        <table class="table table-bordered small-table">
            <thead>
                <tr>
                    <th>Type de facture</th>
                    <th>Date</th>
                    {% if obj.remorque_number %}
                        <th>Remorque N°</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ obj.get_invoice_type_display }}</td>
                    <td>{{ obj.invoice_date_time|date:"d-m-Y" }}</td>
                    {% if obj.remorque_number %}
                        <td>{{ obj.remorque_number }}</td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="table-responsive mt-4">
    <table class="table table-bordered">
        <thead>
            <tr>
                {% if articles.0.order_number %}
                    <th>Colis</th>
                {% endif %}
                <th>Description</th>
                <th>Nbr GB</th>
                <th>Poids/Kg</th>
                <th>Prix U</th>
                <th>Montant Total</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
                <tr>
                    {% if articles.0.order_number %}
                        <td>{{ article.order_number }}</td>
                    {% endif %}
                    <td>{{ article.name }}</td>
                    <td>{{ article.nbre_GB }}</td>
                    <td>{{ article.quantity }}</td>
                    <td>{{ article.unit_price }}€</td>
                    <td>{{ article.get_total }}€</td>
                </tr>
            {% endfor %}
            <!-- Display totals row -->
            <tr>
                <td colspan="{% if articles.0.order_number %}{{ articles|length|add:0 }}{% else %}{{ articles|length }}{% endif %}" class="text-end"><strong>Total</strong></td>
                <!-- Display total_nbr_gb and total_weight -->
                <td><strong>{{ obj.total_nbre_gb }}</strong></td>
                <td><strong>{{ obj.total_poid_kg }}Kg</strong></td>
                <td></td> <!-- Leave empty since it's not applicable for total -->
                <td><strong>{{ obj.get_total }}€</strong></td>
            </tr>
        </tbody>
    </table>
</div>

                <div class="row justify-content-end mt-4">
                    <div class="col-md-4">
                        <div class="text-end">
                            <strong>Statut de paiement:</strong> {% if obj.paid %}<span class="text-success">Payé</span>{% else %}<span class="text-danger">Non payé</span>{% endif %}
                        </div>
                    </div>
                </div>

                <br>

                <div class="invoice-footer">
                    <p><strong>RC:91091-TP:52900494-IF:26110455-ICE:002081133000054-CNSS:1099247 ATTIJARI INTERNATIONAL BANK. RIB 605.640.00001.00000002971.46 <br> CODE SWIFT AIBSMAMT</strong></p>
                </div>

                <div class="print-btn text-center">
                    <button class="btn btn-light" onclick="window.print()">
                        <i class="fas fa-print"></i> Imprimer la facture
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load l10n %} <!-- Load l10n tag to enable date localization -->

{% block content %}
<br><br>

<h2 class="text-center">Liste des factures</h2>
<br>

<div class="form-group">
    <input id="search" class="form-control" type="text" placeholder="Rechercher....">
</div>

<div>
    <table class="table table-striped-columns">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nom </th>
                <th scope="col">Date</th>
                <th scope="col">Total</th>
                <th scope="col">Payé</th>
                <th scope="col">Type de facture</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody id="myTable">
            {% if invoices %}
            {% for facture in invoices %}
            <tr>
                <th scope="row">{{ facture.pk }}</th>
                <td>{{facture.customer.name}}</td>
                <td>{{ facture.invoice_date_time|date:"d-m-Y"|localize }}</td>
                <td>{{ facture.get_total }}</td>
                <td>
                    {% if facture.paid %}
                    <img src="{% static 'images/icon-yes.png' %}" alt="True">
                    {% else %}
                    <img src="{% static 'images/icon-no.png' %}" alt="False">
                    {% endif %}
                </td>
                <td>{{facture.get_invoice_type_display }}</td>
                <td>
                    <a href="{% url 'view-invoice' pk=facture.pk  %}" title="Detail" class="badge text-white bg-success">Voir</a>

                    <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer"
                        class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}"
                        data-customer="{{facture.customer.name}}">Supprimer
                    </button>

                    <button id="btn-invoice-mod" type="button" data-toggle="modal" title="Modifier" data-target="#modifier"
                        data-id="{{facture.pk}}" data-customer="{{facture.customer.name}}"
                        class="badge text-dark bg-warning"> Modifier
                    </button>

                    <a href="{% url 'facture_avoir' pk=facture.pk %}" title="Avoir" class="badge text-white bg-info">Avoir</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="7" class="text-center">Aucune facture trouvée.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<!-- Pagination -->
<div class="pagination justify-content-center">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <!-- Add the "Toute" button -->
            <li class="page-item">
                <a class="page-link" href="?page=all">Toute</a>
            </li>
            {% if invoices.has_other_pages %}
            {% if invoices.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ invoices.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for page_number in invoices.paginator.page_range %}
            <li class="page-item {% if invoices.number == page_number %}active{% endif %}">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endfor %}
            {% if invoices.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ invoices.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
            {% endif %}
        </ul>
    </nav>
</div>
<!-- End Pagination -->


<!-- Modal modifier -->
<div class="modal fade" id="modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Modification</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="post">
            {% csrf_token %}
            <div class="modal-body">

               <input name="id_modified" type="hidden" id="id_modified">

               <label id="label_id" class="text-dark checkbox-inline"> <strong id="strong_id"> Cette facture a été payée ?</strong></label>

               <input type="radio" id="html" name="modified" value="True">
               <label class="text-white bg-primary" for="html">Oui</label>

               <input type="radio" id="css" name="modified" value="False">
               <label class="text-white bg-danger" for="css">Non</label><br>

            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
               <button type="submit" class="btn btn-primary">Enregistrer</button>
            </div>
         </form>
      </div>
   </div>
</div>
<!-- end modal-->

<!-- Modal suppression -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">Supprimer la facture</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">Etes-vous sûr de vouloir supprimer la facture ?</strong></label>

               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                  <button type="submit" class="btn btn-danger">Supprimer</button>
               </div>
            </form>
         </div>

      </div>
   </div>
</div>
<!-- end modal-->

<br><br>

<script type="text/javascript">
    // modification
    $(document).on('click', '#btn-invoice-mod', function(){
        let invoice_id = $(this).data('id');
        let customer = $(this).data('customer');
        $('#id_modified').val(invoice_id);
    })

    // deleting of invoice
    $(document).on('click', '#btn-invoice-sup', function(){
        let invoice_id = $(this).data('id');
        let customer = $(this).data('customer');
        $('#id_supprimer').val(invoice_id);
    })

    // handling "avoir" action
    $(document).on('click', '#btn-invoice-avoir', function(){
        let invoice_id = $(this).data('id');
        alert('Avoir action triggered for invoice ID: ' + invoice_id);
        // Add your custom code for "avoir" action here
    })
</script>

<script>

$(document).ready(function(){
        $("#search").on("keyup", function(){
            var value = $(this).val().toLowerCase();
            $("#myTable tr").each(function() {
                var rowText = $(this).text().toLowerCase();
                if (rowText.indexOf(value) > -1) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        });
    });

</script>

{% endblock %}